app/build.gradle
Lint does complain that Okio is an invalid package
https://github.com/square/okio/issues/58
=> [REVIEW] Release version is not building

.travis.yml, app/build.gradle, app/src/androidTest/java/com/tehmou/rxbookapp/activities/ChooseRepositoryActivityTest.java, app/src/androidTest/java/com/tehmou/rxbookapp/activities/MainActivityTest.java, app/src/androidTest/java/com/tehmou/rxbookapp/activities/utils/SystemAnimations.java, app/src/debug/AndroidManifest.xml
Not adding Travis support as it has a cap of 3GB which is not enough for connected tests.
The connected tests can be run on a local machine for now.
=> [REVIEW] Initial Esspresso implementation

rxandroidarchitecture/build.gradle
Not sure if I am missing something but the master branch is not built. support-annotations is missing in build.gradle.
=> Add support-annotations to dependencies

app/src/main/java/io/reark/rxgithubapp/data/DataLayer.java, app/src/main/java/io/reark/rxgithubapp/network/GitHubService.java, app/src/main/java/io/reark/rxgithubapp/network/ServiceDataLayer.java, app/src/main/java/io/reark/rxgithubapp/network/fetchers/GitHubRepositoryFetcher.java, app/src/main/java/io/reark/rxgithubapp/network/fetchers/GitHubRepositorySearchFetcher.java, reark/src/main/java/io/reark/reark/network/fetchers/Fetcher.java
Content URIs are not perfect match for fetchers, since multiple endpoints
may return the same kind of content, rendering the URIs non-unique and thus
unfit for fetcher identification. Use service meta-URIs instead for this.
=> Use service URIs for fetcher matching

app/src/main/java/io/reark/rxgithubapp/data/stores/GitHubRepositorySearchStore.java, app/src/main/java/io/reark/rxgithubapp/data/stores/GitHubRepositoryStore.java, app/src/main/java/io/reark/rxgithubapp/data/stores/NetworkRequestStatusStore.java, app/src/main/java/io/reark/rxgithubapp/data/stores/UserSettingsStore.java, reark/src/main/java/io/reark/reark/data/store/ContentProviderStore.java, reark/src/main/java/io/reark/reark/data/store/SingleItemContentProviderStore.java
Move db writes into computation thread. Also, avoids writes if the new values are identical to existing ones. This reduces UI flickering when values are updated for no reason.
=> Database writes in computation thread

app/src/main/java/io/reark/rxgithubapp/view/RepositoriesView.java, reark/src/main/java/io/reark/reark/utils/TextWatcherObservable.java
Simply move TextWatcherObservable to the library. Perhaps we an later replace it with another library, but for now it is useful to have.
=> Move TextWatcherObservable to library

reark/src/main/java/io/reark/reark/viewmodels/AbstractViewModel.java
By default ViewModel's subscribe() unsubscribes any existing subscription before re-subscribing. Add a method for skipping this in case we're happy with the existing subscription.
=> Add a method for subscribing only when not subscribed yet

reark/src/main/java/io/reark/reark/data/store/ContentProviderStore.java, reark/src/main/java/io/reark/reark/data/store/SingleItemContentProviderStore.java, reark/src/main/java/io/reark/reark/data/store/StoreItem.java
Map of subjects had an issue with a race condition.
Additionally already created subjects were never cleaned.
Replacing them with a single subject ensures that when
a subscriber finishes the subscrition is being disposed.
Keeping all the logic handling in a single monad makes sure
that all race conditions are handeled properly.
=> Replaced Map of Subjects with a single subject

app/src/main/java/io/reark/rxgithubapp/data/DataLayer.java, app/src/main/java/io/reark/rxgithubapp/data/stores/GitHubRepositorySearchStore.java, app/src/main/java/io/reark/rxgithubapp/data/stores/GitHubRepositoryStore.java, app/src/main/java/io/reark/rxgithubapp/data/stores/NetworkRequestStatusStore.java, app/src/main/java/io/reark/rxgithubapp/data/stores/UserSettingsStore.java, app/src/main/java/io/reark/rxgithubapp/network/fetchers/GitHubRepositoryFetcher.java, app/src/main/java/io/reark/rxgithubapp/network/fetchers/GitHubRepositorySearchFetcher.java, reark/src/main/java/io/reark/reark/data/store/ContentProviderStore.java, reark/src/main/java/io/reark/reark/data/store/SingleItemContentProviderStore.java
Previous store API gave us get/query and put/insert methods. This change tries to bring consistency by using the get/put names for all methods. Also adds a new call for getting observable list of all results, and some basic documentation for the content provider store classes.
=> Modify store get/put API for consistency

reark/src/main/java/io/reark/reark/data/DataStreamNotification.java, reark/src/main/java/io/reark/reark/data/utils/DataLayerUtils.java
The problem with no completed status is that the DataStreamNotification status stream is completely separated from the value stream. As a consequence, there is no guarantee that a completed query results in update in value stream. This could happen e.g. in case a newly fetched value is identical with old value already in the stream.
Solution is to handle status stream onCompleted and value stream onNext separately.
=> Add FETCHING_COMPLETED as a status for DataStreamNotification

README.md, app/src/main/java/io/reark/rxgithubapp/view/RepositoriesView.java, app/src/main/java/io/reark/rxgithubapp/viewmodels/RepositoriesViewModel.java
Debounce restarts timer on each change, whereas throttleLast is sampling on fixed timer. The sampling causes search to be restarted constantly, which quickly uses up our API quota when testing.
=> Use debounce instead of throttleLast to avoid constant searching

reark/build.gradle, reark/gradle-mvn-push.gradle
First build after cleaning currently results in 100 errors, which all come from javadoc generation. Javadoc is apparently a required for Maven artifacts. This change fixes most errors by adding missing dependencies to javadoc classpath.
=> Fix javadoc generation errors by including dependencies

reark/src/androidTest/java/io/reark/reark/data/stores/SimpleMockContentProvider.java, reark/src/androidTest/java/io/reark/reark/data/stores/SingleItemContentProviderStoreTest.java
Instrumentation unit tests for stores to test the APIs. This isn't exhaustive set of tests yet, as I'd like to hear if this makes sense. Some overhead code is needed for the mock content provider / resolver, and I'm not sure if it's possible to make our Travis to run instrumentation tests.
Also, perhaps it would be possible to just use a real SQL provider instead of this mocking?
=> Unit testing for store APIs

app/src/main/AndroidManifest.xml, app/src/main/java/io/reark/rxgithubapp/RxGitHubApp.java, app/src/main/java/io/reark/rxgithubapp/network/NetworkService.java, app/src/main/java/io/reark/rxgithubapp/widget/WidgetService.java
If the application is killed and restarted, the widget stops updating. Reason for this is that our services are sticky, so they are restarted soon after application is killed. However, because the WidgetService onStartCommand doesn't come from WidgetProvider, we are missing the widget id and can't thus update the data. Later when the main app is restarted it doesn't trigger widget update, and thus the widget isn't updated until hitting the update period in appwidget_info.xml.
This PR fixes the issue by changing the services to non-sticky. We can do this since the data won't anyway update unless the main app is running. Additionally we must trigger widget update when the app starts.
Also moved the widget service to a separate process just for easier observation.
=> Fix widget not updating to changing values

app/src/main/java/io/reark/rxgithubapp/viewmodels/RepositoriesViewModel.java
Fixes two minor issues:
1) After fragment resuming (e.g. when returning to app from app switcher) the currently open search is resubmitted due to RepositoriesView.bindInternal() setting the current string again
2) If user changes the search and changes it back within the debounce time limit the search is still resubmitted, even though the effective search didn't change
=> Distinct search string to avoid repeating the search

app/src/main/java/io/reark/rxgithubapp/data/stores/GitHubRepositorySearchStore.java, app/src/main/java/io/reark/rxgithubapp/data/stores/GitHubRepositoryStore.java, app/src/main/java/io/reark/rxgithubapp/data/stores/NetworkRequestStatusStore.java, app/src/main/java/io/reark/rxgithubapp/data/stores/UserSettingsStore.java, app/src/main/java/io/reark/rxgithubapp/pojo/GitHubOwner.java, app/src/main/java/io/reark/rxgithubapp/pojo/GitHubRepository.java, app/src/main/java/io/reark/rxgithubapp/pojo/GitHubRepositorySearch.java, app/src/main/java/io/reark/rxgithubapp/pojo/UserSettings.java, reark/src/androidTest/java/io/reark/reark/data/stores/SingleItemContentProviderStoreTest.java, reark/src/main/java/io/reark/reark/data/store/ContentProviderStore.java
ContentProviderStore is using ContentValues in places where we could use the types instead. Changing to types allows us to remove two methods from the store interface. After this change all store objects are required to implement a valid equals() method, otherwise the persisted values won't be updated.
=> Simplify the store interface by using types more instead of ContentValues

reark/src/main/java/io/reark/reark/data/DataStreamNotification.java
DataStreamNotification currently allows access to the notification type only via the convenience methods for checking individual types. I'm not sure why, as enumerating the state would be often easier. This adds a getter for the type for that purpose.
=> Add getter for datastream notification type

reark/src/main/AndroidManifest.xml, reark/src/main/res/values/strings.xml
Remove unnecessary app label from the manifest because it caused some trouble in manifest merge when building project.
Also removed strings.xml from the library since it's not needed anymore.
=> Remove unnecessary app label from the manifest

.travis.yml, app/build.gradle, appbasic/build.gradle, appshared/build.gradle, build.gradle, reark/build.gradle
Split to multiple modules brought needless duplication to gradle files. This simplifies the situation, and updates the dependencies while at it.
=> Update dependencies and clean gradle files

appshared/src/main/java/io/reark/rxgithubapp/shared/viewmodels/RepositoriesViewModel.java
Small fix: filter only after debounce, otherwise a partial search will be executed when user is clearing the search text box with backspace key. It's annoying when testing.
=> Filter only after debounce

app/src/androidTest/java/io/reark/rxgithubapp/advanced/data/stores/GitHubRepositoryStoreTest.java, app/src/androidTest/java/io/reark/rxgithubapp/advanced/data/stores/cores/GitHubRepositoryStoreCoreTest.java, app/src/main/java/io/reark/rxgithubapp/advanced/data/stores/cores/GitHubRepositoryStoreCore.java, reark/src/androidTest/java/io/reark/reark/data/stores/ContentProviderStoreTest.java, reark/src/main/java/io/reark/reark/data/stores/ContentProviderStore.java, reark/src/main/java/io/reark/reark/data/stores/cores/ContentProviderStoreCore.java, reark/src/main/java/io/reark/reark/data/stores/cores/MemoryStoreCore.java
MemoryStoreCore already contains protected `getStream()` that doesn't filter. It's useful method for extending classes that wish to access all incoming items, so add a similar one for the content provider version.
=> Add getStream for ContentProviderStoreCore

app/src/main/java/io/reark/rxgithubapp/advanced/data/DataLayer.java, app/src/main/java/io/reark/rxgithubapp/advanced/data/schematicProvider/GitHubDatabase.java, app/src/main/java/io/reark/rxgithubapp/advanced/network/ServiceDataLayer.java, app/src/main/java/io/reark/rxgithubapp/advanced/widget/WidgetService.java, appbasic/src/main/java/io/reark/rxgithubapp/basic/data/DataLayer.java, appshared/src/main/java/io/reark/rxgithubapp/shared/data/ClientDataLayerBase.java, appshared/src/main/java/io/reark/rxgithubapp/shared/data/DataFunctions.java, appshared/src/main/java/io/reark/rxgithubapp/shared/network/fetchers/GitHubRepositoryFetcher.java, appshared/src/main/java/io/reark/rxgithubapp/shared/network/fetchers/GitHubRepositorySearchFetcher.java, appshared/src/main/java/io/reark/rxgithubapp/shared/viewmodels/RepositoriesViewModel.java, appshared/src/main/java/io/reark/rxgithubapp/shared/viewmodels/RepositoryViewModel.java, appshared/src/test/java/io/reark/rxgithubapp/shared/viewmodels/RepositoriesViewModelTest.java, appshared/src/test/java/io/reark/rxgithubapp/shared/viewmodels/RepositoryViewModelTest.java, reark/src/main/java/io/reark/reark/network/fetchers/Fetcher.java, reark/src/main/java/io/reark/reark/network/fetchers/FetcherBase.java, reark/src/main/java/io/reark/reark/pojo/NetworkRequestStatus.java
This should fix issue where new requests will start with old request status if the same resource was requester earlier. Idea behind the change is to register all requests with an id, and filter the data stream notifications so that only matching ids are let through.
Additionally the request status store should be cleared at startup to avoid issues caused by duplicate ids across application restarts, but that is pending the delete PR #155.
=> Data notifications should not start with stale status

app/src/main/java/io/reark/rxgithubapp/advanced/data/stores/cores/NetworkRequestStatusStoreCore.java, reark/src/main/java/io/reark/reark/data/stores/cores/ContentProviderStoreCoreBase.java, reark/src/test/java/io/reark/reark/data/stores/cores/ContentProviderStoreCoreBaseTest.java
Fix for https://github.com/reark/reark/issues/162. This solution is not as nice though: when a triggered debounce is followed with a window closing, we'll get two partial buffers one after the other. This could be revisited if a fix for the observed issue is found.
=> Fix grouping logic failure when number of items matches the group size

appshared/src/main/java/io/reark/rxgithubapp/shared/network/GitHubService.java, appshared/src/main/java/io/reark/rxgithubapp/shared/network/NetworkApi.java, appshared/src/main/java/io/reark/rxgithubapp/shared/network/fetchers/GitHubRepositoryFetcher.java, appshared/src/main/java/io/reark/rxgithubapp/shared/network/fetchers/GitHubRepositorySearchFetcher.java, appshared/src/main/java/io/reark/rxgithubapp/shared/viewmodels/RepositoriesViewModel.java, appshared/src/test/java/io/reark/rxgithubapp/shared/viewmodels/RepositoriesViewModelTest.java, reark/src/main/java/io/reark/reark/data/DataStreamNotification.java, reark/src/main/java/io/reark/reark/data/stores/cores/ContentProviderStoreCoreBase.java, reark/src/main/java/io/reark/reark/data/utils/DataLayerUtils.java, reark/src/main/java/io/reark/reark/network/fetchers/FetcherBase.java, reark/src/main/java/io/reark/reark/pojo/NetworkRequestStatus.java
A successful fetch may not change data, in which case observers won't get notified of a change and no ON_NEXT will be emitted. Thus, completed with/without value should be separate states so that any value listeners can decide to end a subscription. Currently that's not possible as they have to keep waiting for ON_NEXT that may or may not come.
=> Separate status for request completed with value change

reark/src/main/java/io/reark/reark/data/stores/cores/ContentProviderStoreCoreBase.java, reark/src/main/java/io/reark/reark/data/stores/cores/operations/CoreOperation.java, reark/src/main/java/io/reark/reark/data/stores/cores/operations/CoreOperationResult.java, reark/src/main/java/io/reark/reark/data/stores/cores/operations/CoreValue.java, reark/src/main/java/io/reark/reark/data/stores/cores/operations/CoreValueDelete.java, reark/src/main/java/io/reark/reark/data/stores/cores/operations/CoreValuePut.java
Fixes content operation result listening mechanism that was prone to race conditions with id put/get. Keeping the result notification subject with the operation avoids the problem entirely.
Additionally fixes threading that wasn't properly applied, and adds missing backpressure handling that was revealed with the improved performance after applying proper threading.
=> Fix content operation result notification mechanism

appshared/src/test/java/io/reark/rxgithubapp/shared/pojo/GitHubRepositoryTest.java, reark/src/main/java/io/reark/reark/pojo/OverwritablePojo.java, reark/src/test/java/io/reark/reark/pojo/OverwritablePojoTest.java
This enables using OvewritablePojo base class with Kotlin value classes where fields are final. Expectation is that the overwriting functionality will only ever be used at object creation time, so this shouldn't cause any issues of unexpected object state.
=> Enable overwriting of final fields in OverwritablePojo

reark/src/main/java/io/reark/reark/data/stores/cores/MemoryStoreCore.java, reark/src/test/java/io/reark/reark/data/stores/cores/MemoryStoreCoreTest.java
Wrong `from` used in the RxJava2 update.
=> Fix MemoryStoreCore to use fromIterable
